### ISSUE TITLE
pls make spydermen game run on this emulatr

### ISSUE THREAD

**Issue by FranklinBartholomewHill** [MystifyCodes/Getting-GPCS4-To-run-other-games-#1]
i really want to play this game. can you help me. my spec is i3-340 gtx 460 4gb ram.

**Comment by MystifyCodes** [comment]
> i really want to play this game. can you help me. my spec is i3-340 gtx 460 4gb ram.

sorry buddy you wont be able to run this emulator with your computer specs and you need to go play with legos it will take some time sorry 👍🏽
